name: eldafit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.0
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_gen: ^5.11.0
  barcode_widget: ^2.0.4
  firebase_messaging: ^16.0.0
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/progress_icon1.png
    - assets/progress_icon2.png
  

flutter_gen:
  output: lib/gen/
  localizations:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    synthetic-package: false