// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrF3Sw_a7IypthlQC99qkH5Sy4dJiKvP0',
    appId: '1:298413566427:web:628209c78669d8c32e1ffe',
    messagingSenderId: '298413566427',
    projectId: 'eldafit',
    authDomain: 'eldafit.firebaseapp.com',
    storageBucket: 'eldafit.firebasestorage.app',
    measurementId: 'G-FVQFLSJKFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHgejZJ1EWcffFvLQ5T6OKWlOx0k_q6Rg',
    appId: '1:298413566427:android:06004411f7cfbf352e1ffe',
    messagingSenderId: '298413566427',
    projectId: 'eldafit',
    storageBucket: 'eldafit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2qZh-ASeYrnT8MPJ-Z2DSGUwgRuFE8k',
    appId: '1:298413566427:ios:65677a167717a8b32e1ffe',
    messagingSenderId: '298413566427',
    projectId: 'eldafit',
    storageBucket: 'eldafit.firebasestorage.app',
    iosClientId: '298413566427-tlqtplpolq4u9fevbfbivn91gtd218ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2qZh-ASeYrnT8MPJ-Z2DSGUwgRuFE8k',
    appId: '1:298413566427:ios:65677a167717a8b32e1ffe',
    messagingSenderId: '298413566427',
    projectId: 'eldafit',
    storageBucket: 'eldafit.firebasestorage.app',
    iosClientId: '298413566427-tlqtplpolq4u9fevbfbivn91gtd218ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.eldafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrF3Sw_a7IypthlQC99qkH5Sy4dJiKvP0',
    appId: '1:298413566427:web:f9696536abf4e2722e1ffe',
    messagingSenderId: '298413566427',
    projectId: 'eldafit',
    authDomain: 'eldafit.firebaseapp.com',
    storageBucket: 'eldafit.firebasestorage.app',
    measurementId: 'G-HW60LVB8X4',
  );
}